metadata:
  annotations:
    configmap.fabric8.io/update-on-change: ${project.artifactId}
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: credentials
          secret:
            secretName: app-credentials
      containers:
        - volumeMounts:
            - name: credentials
              mountPath: /etc/app-credentials
